Friday's changes
googleinterns/static-analyzer pull request #10
Opened 2020-08-10 17:18 UTC by Agubuzoboy

2020-08-10 18:29 UTC, devadigar commented on readme.txt
> +    The tool automatically installs the static analyzer dependecies (th estatic analyzers used in this tool). Here is a list of the current installations
Fix Typo.

2020-08-10 18:33 UTC, devadigar commented on readme.txt
I remember we discussed about adding additional details around debugging sonarqube server status, which port sever is running command to check the status. How to bring up server manually, if needed etc...

You can separate heading about Sonarqube and these details

2020-08-10 19:02 UTC, devadigar commented on readme.txt
>      Python3, pip, and java are required dependecies
To make it clear, you can add these pre-req under separate "Pre-requisites" section

2020-08-10 19:10 UTC, devadigar requested changes
2 small ReadME changes needed, otherwise looks good.

2020-08-11 17:46 UTC, devadigar approved these changes

2020-08-11 17:47 UTC, devadigar approved these changes

2020-08-11 21:11 UTC, xuchenma approved these changes

2020-08-11 21:16 UTC, merged